name = "Umbrella"
uuid = "fb3c7edd-4d33-4ece-bf81-49ff2d418a94"
authors = ["Jiacheng Zhang <zhangjiacheng54@gmail.com>"]
version = "0.1.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
JSON3 = "1"
HTTP = "0.8 - 1.0"
julia = "1.6 - 1.7"
StructTypes = "1.8"
URIs = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"

[targets]
test = ["Test"]